project:
  type: website
  output-dir: docs

website:
  title: "<span style= 'font-size: 24px;'> 💊 Drug Consumption and Prevention </span>"
  navbar:
    left:
      - text: About
        menu:
          - text: Overview
            href: index.qmd
          - text: Research Question
            href: ResearchQuestion.qmd
      - text: Data Analysis
        menu: 
          - text: Demographic Characteristics
            href: Univariate.qmd
          - text: Psychological Traits
            href: Personality.qmd
      - text: Conclusion
        href: Conclusion.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

