---
title: "<span style='font-size: 30px;'> Conclusion </span>"
---

Let's review the **research question** first.

[How do [demographic characteristics](Univariate.qmd) and [psychological traits](Personality.qmd) (i.e., personality) influence the frequency and type of drug consumption?]{style="background-color:#fdfd96;"}

As the detailed pages have already summarized each finding under the respective subtitles, this conclusion section will adopt a more engaging Q&A format. Please note that this page will be continuously updated. If you would like to contribute, please feel free to drop an email to the author or provide your feedback on the feedback panel at the bottom of this page!

## About different drugs

### Alcohol 

A Legal Staple with Minimal Personality Impact?

**Q: How does alcohol consumption vary among participants?**

A: Alcohol is a common fixture in the lives of the study's participants, with younger people tending to drink more frequently. Despite minor gender differences, the general pattern of alcohol consumption is similar across the board.

**Q: What's the relationship between alcohol and personality traits?**

A: Interestingly, alcohol consumption doesn't seem to demonstrate a significant relationship with any of the Big Five personality traits. This suggests that, while popular, alcohol may not be a defining factor in shaping these particular aspects of personality.

### Caffeine

A Daily Ritual Across Demographics

**Q: Is caffeine as widely consumed as alcohol?**

A: Absolutely, caffeine consumption is a daily ritual for the majority of participants, showing a decline with age but little variation across genders or countries.

**Q: Does personality scores influence caffeine consumption?**

A: Like alcohol, caffeine intake doesn't present a strong link to the Big Five personality traits. It appears to be a universal habit with limited impact on the personality measures in question.

### Nicotine

Divergent Usage with Subtle Personality Ties

**Q: Can we see clear patterns in nicotine consumption?**

A: Nicotine use is divided, with a significant portion never using it and others using it daily. Men and those with less education are more inclined toward regular use, while older age groups show a trend of non-consumption.

**Q: What's the effect of nicotine on personality?**

A: There's a hint of a weak negative relationship between nicotine consumption and Agreeableness and Conscientiousness scores, but the overall impact on personality is not strongly pronounced.

### Cannabis

A Controversial Substance with Notable Personality Links

**Q: How common is cannabis use among the participants?**

A: Cannabis consumption patterns reveal that it's less common than legal drugs, with more frequent use among younger males and a trend toward non-consumption with higher education.

**Q: Does cannabis use correlate with personality traits?**

A: Yes, cannabis shows a positive correlation with Neuroticism and Openness, suggesting that its use might be associated with certain personality dimensions more so than legal drugs.

### Cocaine

An Illegal Drug with a Defined Personality Profile?

**Q: What are the consumption trends for cocaine?**

A: Cocaine is the least consumed among the substances studied, with a higher prevalence of use among younger individuals and men in the past decade. Usage does not significantly vary with education level.

**Q: Are there personality traits associated with cocaine use?**

A: Cocaine consumption is negatively related to Agreeableness and Conscientiousness, with some indications of a negative impact on Extraversion. It also correlates positively with Neuroticism, suggesting a more pronounced personality profile among users.

### Heroin

Rare Use with Clear Personality Implications

**Q: Is heroin usage as low as cocaine?**

A: Yes, heroin has a similar low consumption level, with most participants reporting they've never used it. Its use decreases with age, and there are no notable gender or educational differences.

**Q: How does heroin relate to personality scores?**

A: Heroin usage exhibits a negative relationship with Agreeableness and Conscientiousness and may negatively affect Extraversion. Like cocaine, heroin use shows a positive correlation with Neuroticism, aligning with a more defined personality impact. There's also a suggestion of a positive relationship with Openness, though this seems to plateau at higher consumption levels.

## About general trends

### Trend Analysis

Substance Legality and Personality Impact

**Q: Do legal and illegal drugs show different impacts on personality?**

A: Indeed, legal drugs such as alcohol, caffeine, and nicotine have a minimal effect on personality scores, whereas the controversial and illegal substances, cannabis, cocaine, and heroin, show stronger associations with certain personality traits.

**Q: Could the legality of these substances influence consumption patterns?**

A: The legality of a substance definitely influences consumption patterns. Legal drugs are more regularly consumed across a wider demographic, reflecting societal norms and acceptance. However, consumption of illegal drugs like cocaine and heroin is less frequent and often concentrated in specific age groups or demographics, likely due to legal restrictions and associated social stigma. Despite this, the influence of illegal drugs on personality scores is more significant, suggesting that their use, albeit less common, may have a more profound impact on certain personality traits compared to legal substances. This underscores the complex relationship between the legal status of a drug, its societal perception, and its potential psychological effects.

## Feedback
If you have any feedback or suggestions for improvement, please feel free to share them here:

```{=html}
<iframe height="50%" width="100%" frameborder="no" src="https://yolanda699.shinyapps.io/app2/"> </iframe>
```
